################
# DrupalCI GitLabCI template
#
# Gitlab-ci.yml to replicate DrupalCI testing for Contrib
#
# With thanks to:
#   * The GitLab Acceleration Initiative participants
#   * DrupalSpoons
################

################
# Guidelines
#
# This template is designed to give any Contrib maintainer everything they need to test, without requiring modification. It is also designed to keep up to date with Core Development automatically through the use of include files that can be centrally maintained.
#
# However, you can modify this template if you have additional needs for your project.
################

################
# Includes
#
# Additional configuration can be provided through includes.
# One advantage of include files is that if they are updated upstream, the changes affect all pipelines using that include.
#
# Includes can be overridden by re-declaring anything provided in an include, here in gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/yaml/includes.html#override-included-configuration-values
################

include:
  #################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  #################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Pipeline configuration variables
#
# These are the variables provided to the Run Pipeline form that a user may want to override.
#
# Docs at https://git.drupalcode.org/project/gitlab_templates/-/blob/1.0.x/includes/include.drupalci.variables.yml
################

variables:
  SKIP_CSPELL: "1"
  _PHPUNIT_CONCURRENT: '1'
#  _PHPUNIT_EXTRA: '-c $CI_PROJECT_DIR/$_WEB_ROOT/core --testdox --colors=always'
#  SKIP_PHPUNIT: '0'
  BROWSERTEST_OUTPUT_VERBOSE: 'false'
  OPT_IN_TEST_PREVIOUS_MAJOR: '0'
  OPT_IN_TEST_PREVIOUS_MINOR: '0'
  OPT_IN_TEST_NEXT_MINOR: '1'
  OPT_IN_TEST_NEXT_MAJOR: '0'
  PHPUNIT_FAIL_ON_PHPUNIT_DEPRECATION: true

phpunit:
  extends: .phpunit-base
  variables:
    SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=$CI_PROJECT_DIR/$_WEB_ROOT/modules/custom/image_effects/.deprecation-ignore.txt"
  before_script:
    # Merge core's deprecation ignore file into module's.
    - cat $CI_PROJECT_DIR/$_WEB_ROOT/core/.deprecation-ignore.txt >> $CI_PROJECT_DIR/$_WEB_ROOT/modules/custom/image_effects/.deprecation-ignore.txt
    # Install both ImageMagick and GraphicsMagick packages.
    - echo -e "\e[0Ksection_start:`date +%s`:package_install[collapsed=true]\r\e[0K\e[0;30;103m *** ImageMagick and GraphicsMagick packages install *** \e[0m"
    - sudo apt-get update
    - sudo apt-get install -y --no-install-recommends imagemagick graphicsmagick ghostscript-x
    - echo -e "\e[0Ksection_end:`date +%s`:package_install\r\e[0K"
    # Print packages' versions.
    - |
      convert -version | head -n1
      gm -version | head -n1
      gs -version | head -n1
